// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoPetShop.Data;

namespace ProjetoPetShop.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20221024235542_PetDB")]
    partial class PetDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ProjetoPetShop.Model.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProjetoPetShop.Model.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Deficiencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("NomePet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("clienteIdCliente")
                        .HasColumnType("int");

                    b.HasKey("IdPet");

                    b.HasIndex("clienteIdCliente");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("ProjetoPetShop.Model.Pet", b =>
                {
                    b.HasOne("ProjetoPetShop.Model.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteIdCliente");

                    b.Navigation("cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
