// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoPetShop.Data;

namespace ProjetoPetShop.Migrations
{
    [DbContext(typeof(PetContext))]
    partial class PetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ProjetoPetShop.Model.Servico", b =>
                {
                    b.Property<int>("idServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tipoServico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("valor")
                        .HasColumnType("double");

                    b.HasKey("idServico");

                    b.ToTable("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
